### ISSUE TITLE
Nystrom for Image processing

### ISSUE THREAD

**Issue by paragon1234** [lucidrains/nystrom-attention#10]
thank you for sharing the wondeful code. I am working on image processing and wanted to try your code for the same. I have 2 doubts:
1) How to select residual_conv_kernel? I could not find any details for the same. also, it is enabled by a flag. When should we enable it and when to disable it?
2) Is there any guideline for deciding num_landmarks for image processing task?

Thanks

**Comment by RobertHua96** [comment]
This should help (from the paper's authors) [](https://github.com/mlpen/Nystromformer/issues/5)

https://github.com/mlpen/Nystromformer/issues/5 

TLDR no need for residual conv for image tasks.
