### ISSUE TITLE
Relative position encoding

### ISSUE THREAD

**Issue by jdcla** [lucidrains/nystrom-attention#4]
Similar to [the question](https://github.com/lucidrains/performer-pytorch/issues/19) raised for the performer architecture , is it possible to implement a relative position encoding given the methodology in which attention is calculated?

**Comment by lucidrains** [comment]
@jdcla there may be a way to make it work by biasing the attention matrix (m x n) and (n x m) using T5 relative positional embedding trick https://github.com/lucidrains/x-transformers#t5s-simplified-relative-positional-encoding I'm not too sure about the (m x m) matrix though
