### ISSUE TITLE
Possible bug with padding

### ISSUE THREAD

**Issue by georgepar** [lucidrains/nystrom-attention#5]
Hey there,

I was going through the code and I noticed the following, which I found curious.

In [Line 75](https://github.com/lucidrains/nystrom-attention/blob/main/nystrom_attention/nystrom_attention.py#L75), you pad the input tensor to a multiple of num_landmarks from the front:

```
x = F.pad(x, (0, 0, padding, 0), value = 0)
```

In [Line 144](https://github.com/lucidrains/nystrom-attention/blob/main/nystrom_attention/nystrom_attention.py#L144) you trim the extra padding elements you inserted in the output tensor from the end.

```
out = out[:, :n]
```

Am I not getting something, or should we be removing the front elements of out?

```
out = out[:, out.size(1) - n:]
```

**Comment by lucidrains** [comment]
@georgepar Hi Giorgos! You indeed found a bug, thank you, and I am sorry if this caused any troubles with your research :(

**Comment by georgepar** [comment]
No trouble at all. Thanks for your awesome work :)
